# Generated by Django 4.2.3 on 2023-08-08 19:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import websiteProject.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[websiteProject.web.validators.TextAndNumsOnlyValidator])),
                ('genre', models.CharField(choices=[('FAN', 'Fantasy'), ('SCIF', 'Sci-Fi'), ('NFAN', 'Nonfiction')], max_length=255)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('cover_url', models.URLField()),
                ('book', models.TextField()),
                ('posted_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2), websiteProject.web.validators.TextAndNumsOnlyValidator])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('posted_on', models.DateTimeField(blank=True, null=True)),
                ('book_commented_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.profile'),
        ),
    ]
