# Generated by Django 4.2.3 on 2023-08-02 15:08

import django.core.validators
from django.db import migrations, models
import websiteProject.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default=1, max_length=30, validators=[django.core.validators.MinLengthValidator(6), websiteProject.web.validators.TextAndNumsOnlyValidator]),
            preserve_default=False,
        ),
    ]
