# Generated by Django 4.2.3 on 2023-08-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(default=1, upload_to='static/books/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(upload_to='static/covers/'),
        ),
    ]
