genre_choices = [
    ("Fantasy", "Fantasy"),
    ("Sci-Fi", "Sci-Fi"),
    ("Nonfiction", "Nonfiction"),
    ("Mystery", "Mystery"),
    ("Thriller", "Thriller"),
    ("Romance", "Romance"),
    ("Historical Fiction", "Historical Fiction"),
    ("Adventure", "Adventure"),
    ("Horror", "Horror"),
    ("Drama", "Drama"),
    ("Comedy", "Comedy"),
    ("Biography", "Biography"),
    ("Self-Help", "Self-Help"),
    ("Science", "Science"),
    ("Poetry", "Poetry"),
]
